### ISSUE TITLE
INDEX keyword

### ISSUE THREAD

**Issue by HalfVoxel** [cmancone/mygrations#2]
The parser does not seem to support the INDEX keyword. According to the mysql documentation it should be equivalent to KEY which does work in this package, but it is slightly confusing when it fails with an error.

**Comment by cmancone** [comment]
Thanks @HalfVoxel.  Since you've obviously been looking at this I figured I'd let you know - I've been using this in production at my office for about 6 months, and have a small bug list myself that I've been meaning to get to.  I'll see if I can make some room in my schedule in the next week or two.

**Comment by HalfVoxel** [comment]
Nice!
Yeah I found it to be a really nice library, but I have reverted now to more common migration files because it I could often not figure out in what format this library wanted things.

**Comment by cmancone** [comment]
@HalfVoxel I'm actually suspicious that I should replace the SQL parser for a more robust one - python has a few available as third party libraries that I could try out.  Most of them are focused on more typical use cases though - SELECT, INSERT, UPDATE, etc... which (other than INSERT) will probably never be used in this library.  As a result (and due to my own desire to experiment) I wrote my own very basic parser.  Unfortunately as a result I've occasionally encountered issues myself when it was reporting a parser error but I wasn't even clear exactly what the issue was.

**Comment by cmancone** [comment]
Feel free to open issues with SQL samples that give confusing results on what is actually wrong.  If it can't give a clear error message then that is a problem.

**Comment by HalfVoxel** [comment]
Sure.
Here is a sample file that you can use for testing:
~~~
CREATE TABLE `webshop_product_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `webshop_product_images` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(10) unsigned NOT NULL,
  `path` varchar(255) COLLATE utf8mb4_unicode_ci,
  `caption` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
);

CREATE TABLE `webshop_products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `unit` varchar(30) COLLATE utf8mb4_unicode_ci,
  `price` decimal(15,2) NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `category_id_key` (category_id),
  CONSTRAINT category_constraint FOREIGN KEY (`category_id`) REFERENCES `webshop_product_categories` (`id`)
);

CREATE TABLE `webshop_product_variants` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci,
  `price` decimal(15,2) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `webshop_transactions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `member_id` int(10) unsigned NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE `webshop_transaction_contents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `transaction_id` int(10) unsigned NOT NULL,
  `product_id` int(10) unsigned NOT NULL,
  `count` int(10) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `transaction_id_key` (transaction_id),
  CONSTRAINT transaction_constraint FOREIGN KEY (`transaction_id`) REFERENCES `webshop_transactions` (`id`)
);
~~~

I'm pretty sure it failed on the "ON UPDATE" part among other things.

**Comment by HalfVoxel** [comment]
Replacing the SQL parser might be a good idea, but you'll have to be very careful to either get one that actually supports the whole necessary grammar, or one that you can easily extend.
